export const countries = [
  { code: 'BR', name: 'Brasil', dial: '+55' },
  { code: 'US', name: 'Estados Unidos', dial: '+1' },
  { code: 'GB', name: 'Reino Unido', dial: '+44' },
  { code: 'PT', name: 'Portugal', dial: '+351' },
  { code: 'ES', name: 'Espanha', dial: '+34' },
  { code: 'FR', name: 'França', dial: '+33' },
  { code: 'DE', name: 'Alemanha', dial: '+49' },
  { code: 'IT', name: 'Itália', dial: '+39' },
  { code: 'AR', name: 'Argentina', dial: '+54' },
  { code: 'MX', name: 'México', dial: '+52' },
  { code: 'CL', name: 'Chile', dial: '+56' },
  { code: 'CO', name: 'Colômbia', dial: '+57' },
  { code: 'PE', name: 'Peru', dial: '+51' },
  { code: 'VE', name: 'Venezuela', dial: '+58' },
  { code: 'UY', name: 'Uruguai', dial: '+598' },
  { code: 'PY', name: 'Paraguai', dial: '+595' },
  { code: 'BO', name: 'Bolívia', dial: '+591' },
  { code: 'EC', name: 'Equador', dial: '+593' },
  { code: 'CA', name: 'Canadá', dial: '+1' },
  { code: 'AU', name: 'Austrália', dial: '+61' },
  { code: 'NZ', name: 'Nova Zelândia', dial: '+64' },
  { code: 'JP', name: 'Japão', dial: '+81' },
  { code: 'CN', name: 'China', dial: '+86' },
  { code: 'KR', name: 'Coreia do Sul', dial: '+82' },
  { code: 'IN', name: 'Índia', dial: '+91' },
  { code: 'RU', name: 'Rússia', dial: '+7' },
  { code: 'ZA', name: 'África do Sul', dial: '+27' },
  { code: 'EG', name: 'Egito', dial: '+20' },
  { code: 'NG', name: 'Nigéria', dial: '+234' },
  { code: 'KE', name: 'Quênia', dial: '+254' },
  { code: 'SA', name: 'Arábia Saudita', dial: '+966' },
  { code: 'AE', name: 'Emirados Árabes', dial: '+971' },
  { code: 'IL', name: 'Israel', dial: '+972' },
  { code: 'TR', name: 'Turquia', dial: '+90' },
  { code: 'GR', name: 'Grécia', dial: '+30' },
  { code: 'NL', name: 'Holanda', dial: '+31' },
  { code: 'BE', name: 'Bélgica', dial: '+32' },
  { code: 'CH', name: 'Suíça', dial: '+41' },
  { code: 'AT', name: 'Áustria', dial: '+43' },
  { code: 'SE', name: 'Suécia', dial: '+46' },
  { code: 'NO', name: 'Noruega', dial: '+47' },
  { code: 'DK', name: 'Dinamarca', dial: '+45' },
  { code: 'FI', name: 'Finlândia', dial: '+358' },
  { code: 'PL', name: 'Polônia', dial: '+48' },
  { code: 'CZ', name: 'República Tcheca', dial: '+420' },
  { code: 'HU', name: 'Hungria', dial: '+36' },
  { code: 'RO', name: 'Romênia', dial: '+40' },
  { code: 'IE', name: 'Irlanda', dial: '+353' },
  { code: 'SG', name: 'Singapura', dial: '+65' },
  { code: 'MY', name: 'Malásia', dial: '+60' },
  { code: 'TH', name: 'Tailândia', dial: '+66' },
  { code: 'VN', name: 'Vietnã', dial: '+84' },
  { code: 'PH', name: 'Filipinas', dial: '+63' },
  { code: 'ID', name: 'Indonésia', dial: '+62' },
  { code: 'PK', name: 'Paquistão', dial: '+92' },
  { code: 'BD', name: 'Bangladesh', dial: '+880' },
  { code: 'AF', name: 'Afeganistão', dial: '+93' },
  { code: 'AL', name: 'Albânia', dial: '+355' },
  { code: 'DZ', name: 'Argélia', dial: '+213' },
  { code: 'AD', name: 'Andorra', dial: '+376' },
  { code: 'AO', name: 'Angola', dial: '+244' },
  { code: 'AG', name: 'Antígua e Barbuda', dial: '+1-268' },
  { code: 'AM', name: 'Armênia', dial: '+374' },
  { code: 'AZ', name: 'Azerbaijão', dial: '+994' },
  { code: 'BS', name: 'Bahamas', dial: '+1-242' },
  { code: 'BH', name: 'Bahrein', dial: '+973' },
  { code: 'BB', name: 'Barbados', dial: '+1-246' },
  { code: 'BY', name: 'Bielorrússia', dial: '+375' },
  { code: 'BZ', name: 'Belize', dial: '+501' },
  { code: 'BJ', name: 'Benin', dial: '+229' },
  { code: 'BT', name: 'Butão', dial: '+975' },
  { code: 'BA', name: 'Bósnia e Herzegovina', dial: '+387' },
  { code: 'BW', name: 'Botsuana', dial: '+267' },
  { code: 'BN', name: 'Brunei', dial: '+673' },
  { code: 'BG', name: 'Bulgária', dial: '+359' },
  { code: 'BF', name: 'Burkina Faso', dial: '+226' },
  { code: 'BI', name: 'Burundi', dial: '+257' },
  { code: 'KH', name: 'Camboja', dial: '+855' },
  { code: 'CM', name: 'Camarões', dial: '+237' },
  { code: 'CV', name: 'Cabo Verde', dial: '+238' },
  { code: 'CF', name: 'República Centro-Africana', dial: '+236' },
  { code: 'TD', name: 'Chade', dial: '+235' },
  { code: 'CR', name: 'Costa Rica', dial: '+506' },
  { code: 'HR', name: 'Croácia', dial: '+385' },
  { code: 'CU', name: 'Cuba', dial: '+53' },
  { code: 'CY', name: 'Chipre', dial: '+357' },
  { code: 'CI', name: 'Costa do Marfim', dial: '+225' },
  { code: 'CD', name: 'República Democrática do Congo', dial: '+243' },
  { code: 'DJ', name: 'Djibuti', dial: '+253' },
  { code: 'DM', name: 'Dominica', dial: '+1-767' },
  { code: 'DO', name: 'República Dominicana', dial: '+1-809' },
  { code: 'TL', name: 'Timor-Leste', dial: '+670' },
  { code: 'SV', name: 'El Salvador', dial: '+503' },
  { code: 'GQ', name: 'Guiné Equatorial', dial: '+240' },
  { code: 'ER', name: 'Eritreia', dial: '+291' },
  { code: 'EE', name: 'Estônia', dial: '+372' },
  { code: 'ET', name: 'Etiópia', dial: '+251' },
  { code: 'FJ', name: 'Fiji', dial: '+679' },
  { code: 'GA', name: 'Gabão', dial: '+241' },
  { code: 'GM', name: 'Gâmbia', dial: '+220' },
  { code: 'GE', name: 'Geórgia', dial: '+995' },
  { code: 'GH', name: 'Gana', dial: '+233' },
  { code: 'GD', name: 'Granada', dial: '+1-473' },
  { code: 'GT', name: 'Guatemala', dial: '+502' },
  { code: 'GN', name: 'Guiné', dial: '+224' },
  { code: 'GW', name: 'Guiné-Bissau', dial: '+245' },
  { code: 'GY', name: 'Guiana', dial: '+592' },
  { code: 'HT', name: 'Haiti', dial: '+509' },
  { code: 'HN', name: 'Honduras', dial: '+504' },
  { code: 'IS', name: 'Islândia', dial: '+354' },
  { code: 'IQ', name: 'Iraque', dial: '+964' },
  { code: 'IR', name: 'Irã', dial: '+98' },
  { code: 'JM', name: 'Jamaica', dial: '+1-876' },
  { code: 'JO', name: 'Jordânia', dial: '+962' },
  { code: 'KZ', name: 'Cazaquistão', dial: '+7' },
  { code: 'KW', name: 'Kuwait', dial: '+965' },
  { code: 'KG', name: 'Quirguistão', dial: '+996' },
  { code: 'LA', name: 'Laos', dial: '+856' },
  { code: 'LV', name: 'Letônia', dial: '+371' },
  { code: 'LB', name: 'Líbano', dial: '+961' },
  { code: 'LS', name: 'Lesoto', dial: '+266' },
  { code: 'LR', name: 'Libéria', dial: '+231' },
  { code: 'LY', name: 'Líbia', dial: '+218' },
  { code: 'LI', name: 'Liechtenstein', dial: '+423' },
  { code: 'LT', name: 'Lituânia', dial: '+370' },
  { code: 'LU', name: 'Luxemburgo', dial: '+352' },
  { code: 'MK', name: 'Macedônia do Norte', dial: '+389' },
  { code: 'MG', name: 'Madagascar', dial: '+261' },
  { code: 'MW', name: 'Malawi', dial: '+265' },
  { code: 'MV', name: 'Maldivas', dial: '+960' },
  { code: 'ML', name: 'Mali', dial: '+223' },
  { code: 'MT', name: 'Malta', dial: '+356' },
  { code: 'MH', name: 'Ilhas Marshall', dial: '+692' },
  { code: 'MR', name: 'Mauritânia', dial: '+222' },
  { code: 'MU', name: 'Maurício', dial: '+230' },
  { code: 'FM', name: 'Micronésia', dial: '+691' },
  { code: 'MD', name: 'Moldávia', dial: '+373' },
  { code: 'MC', name: 'Mônaco', dial: '+377' },
  { code: 'MN', name: 'Mongólia', dial: '+976' },
  { code: 'ME', name: 'Montenegro', dial: '+382' },
  { code: 'MA', name: 'Marrocos', dial: '+212' },
  { code: 'MZ', name: 'Moçambique', dial: '+258' },
  { code: 'MM', name: 'Mianmar', dial: '+95' },
  { code: 'NA', name: 'Namíbia', dial: '+264' },
  { code: 'NR', name: 'Nauru', dial: '+674' },
  { code: 'NP', name: 'Nepal', dial: '+977' },
  { code: 'NI', name: 'Nicarágua', dial: '+505' },
  { code: 'NE', name: 'Níger', dial: '+227' },
  { code: 'OM', name: 'Omã', dial: '+968' },
  { code: 'PW', name: 'Palau', dial: '+680' },
  { code: 'PS', name: 'Palestina', dial: '+970' },
  { code: 'PA', name: 'Panamá', dial: '+507' },
  { code: 'PG', name: 'Papua-Nova Guiné', dial: '+675' },
  { code: 'QA', name: 'Catar', dial: '+974' },
  { code: 'CG', name: 'Congo', dial: '+242' },
  { code: 'RW', name: 'Ruanda', dial: '+250' },
  { code: 'KN', name: 'São Cristóvão e Névis', dial: '+1-869' },
  { code: 'LC', name: 'Santa Lúcia', dial: '+1-758' },
  { code: 'VC', name: 'São Vicente e Granadinas', dial: '+1-784' },
  { code: 'WS', name: 'Samoa', dial: '+685' },
  { code: 'SM', name: 'San Marino', dial: '+378' },
  { code: 'ST', name: 'São Tomé e Príncipe', dial: '+239' },
  { code: 'SN', name: 'Senegal', dial: '+221' },
  { code: 'RS', name: 'Sérvia', dial: '+381' },
  { code: 'SC', name: 'Seychelles', dial: '+248' },
  { code: 'SL', name: 'Serra Leoa', dial: '+232' },
  { code: 'SK', name: 'Eslováquia', dial: '+421' },
  { code: 'SI', name: 'Eslovênia', dial: '+386' },
  { code: 'SB', name: 'Ilhas Salomão', dial: '+677' },
  { code: 'SO', name: 'Somália', dial: '+252' },
  { code: 'SS', name: 'Sudão do Sul', dial: '+211' },
  { code: 'LK', name: 'Sri Lanka', dial: '+94' },
  { code: 'SD', name: 'Sudão', dial: '+249' },
  { code: 'SR', name: 'Suriname', dial: '+597' },
  { code: 'SZ', name: 'Suazilândia', dial: '+268' },
  { code: 'SY', name: 'Síria', dial: '+963' },
  { code: 'TJ', name: 'Tajiquistão', dial: '+992' },
  { code: 'TZ', name: 'Tanzânia', dial: '+255' },
  { code: 'TG', name: 'Togo', dial: '+228' },
  { code: 'TO', name: 'Tonga', dial: '+676' },
  { code: 'TT', name: 'Trinidad e Tobago', dial: '+1-868' },
  { code: 'TN', name: 'Tunísia', dial: '+216' },
  { code: 'TM', name: 'Turcomenistão', dial: '+993' },
  { code: 'TV', name: 'Tuvalu', dial: '+688' },
  { code: 'UG', name: 'Uganda', dial: '+256' },
  { code: 'UA', name: 'Ucrânia', dial: '+380' },
  { code: 'UZ', name: 'Uzbequistão', dial: '+998' },
  { code: 'VU', name: 'Vanuatu', dial: '+678' },
  { code: 'VA', name: 'Vaticano', dial: '+39' },
  { code: 'YE', name: 'Iêmen', dial: '+967' },
  { code: 'ZM', name: 'Zâmbia', dial: '+260' },
  { code: 'ZW', name: 'Zimbábue', dial: '+263' },
];