// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teignlrqltptrhqghoqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaWdubHJxbHRwdHJocWdob3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMjQ5NTMsImV4cCI6MjA3NzcwMDk1M30.qs7UDx2L8DzrpR9VLjfS-VaqIItWNPz7ZqPocRv6bTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});